apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: redirect-secret
spec:
  refreshInterval: 1h          # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: redirect-secret  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "REDIRECT_KEY"
      remoteRef:
        key: jenuine-prod-redirect-key
        version: latest
