{
 "title": "006 - Users Devices List",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Connections By Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections By Users",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(count_over_time({type=\"syslog\", category=\"firewall\"}[$__interval])) by (possible_user)",
     "legendFormat": "{{possible_user}}"
    }
   ]
  },
  { "title": "Connections By Src IPs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Connections By Src IPs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(count_over_time({type=\"syslog\", category=\"firewall\"}[$__interval])) by (src_ip)",
     "legendFormat": "{{src_ip}}"
    }
   ]
  },
  { "title": "Connections By Src IPs - Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Connections By Src IPs - Users",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(count_over_time({type=\"syslog\", category=\"firewall\"}[$__interval])) by (src_ip, possible_user)",
     "legendFormat": "{{src_ip}} [{{ possible_user}}]"
    }
   ]
  }
 ]
}